### ISSUE TITLE
Vorschlag! 

### ISSUE THREAD

**Issue by Bottelneck** [Support-pp/Support-pp#22]
Hey, euer Support-Bot ist der Hammer, allerdings würde ich mich über eine weitere Funktion sehr freuen.

Und zwar soll man mit dieser Funktion Supporter vom Support ausschließen können, sobald sie einen bestimmen Rang haben. 

Beispiel: Supporter setzt sich den Rang Kaffeepause, nun wird dieser nicht mehr angestupst, da er den Rang Kaffeepause besitzt. 
Wäre sinnvoll wenn man Supportern ab und zu mal eine Pause gönnen möchte :)

Mal schauen ob euch dieser Vorschlag gefällt.
Auch wenn es damit nichts werden sollte feier ich euren Bot und bedanke mich fürs entwickeln!

Vielen Dank fürs Lesen 🗡  

Mit freundlichen Grüßen 

Bottelneck

**Comment by VerHext** [comment]
Gute Idee, Kaffeepause Module kommt in die Weihnachts Version mit rein...

**Comment by VerHext** [comment]
@Bottelneck wir haben dein Vorschlag in der Version 2.0.4.9-2.3 umgesetzt.
https://medium.com/support-pp/update-2-0-4-9-2-3-8f7ee72dfdfb
