### ISSUE TITLE
Vorschlag für Support++

### ISSUE THREAD

**Issue by SandexYT** [Support-pp/Support-pp#27]
Guten Tag,

Ich hätte den Vorschlag, eine definierte Nachricht an einen User zu schicken, wenn das Themen Modul aktiviert ist und kein Supporter des jeweils ausgewählten Thema online ist.

Mit freundlichen Grüßen
SandexYT | Erwin

**Comment by esieben1310** [comment]
Ich habe deinen Vorschlag überprüft und habe festgestellt, dass es diese Funktion bereits gibt. Sobald kein Supporter für das ausgewählte Thema online ist, wird die Standard Nachricht, wenn kein Supporter online ist ausgegeben.
