### ISSUE TITLE
I have three suggestions for improvement.

### ISSUE THREAD

**Issue by ClashofJustYT** [Support-pp/Support-pp#31]
Dear Support ++ Team,

I have three suggestions for improvement.

It would be nice if you get the feedback message until you move the person into the respective channel. Because most of the time the users receive the message at the very beginning.

Could you do it so that you can only choose one topic message for support. Because the users spam otherwise.

The page https://vcircle.eu/ does not work anymore. For the sounds.

Yours sincerely

Justin

**Comment by VerHext** [comment]
Thanky for your Issues.

1. Ok, add to ToDo
2. Yes, will add a function to steh spam protection module.

3. We don't know this Domain `https://vcircle.eu/` Wher do you get this? On our offical documentation? 
You can finde our Sounds on https://sounds.support-pp.de and the creater of that: http://timvida.de/

**Comment by SpieleArena** [comment]
@VerHext i have seen this url in the code von spp! -> Line **1180** from the newest release:
`        title: '-> Special thanks for the professional sound records to 006mi4. Check out his website: https://vcircle.eu/',`
