### ISSUE TITLE
Queue + Themennotification Issue

### ISSUE THREAD

**Issue by TheUndex** [Support-pp/Support-pp#36]
Hey,

ich hatte mir jetzt die neuste Version des Support++ Scripts installiert und mir ist da direkt etwas aufgefallen. Das Problem ist, dass wenn ein User in den Channel mit dem Bot geht, wird dieser ersteinmal einen Nachricht bekommen und soll aus den verschiedenen Themen wählen. Erst wenn ein Thema ausgewählt wurde, spielt der ausgewählte Track ab. Jedoch sollte es nach meiner Meinung der Fall sein, wenn ich in den Channel joine, der ausgewählte Track sofort abspielt.

Außerdem kann ich keinen der Standard-Tracks abspielen. Kann an mir liegen, dass der die nicht vom Server holt, aber das ist auch ein Problem welches ich momentan habe...

LG Undex

**Comment by VerHext** [comment]
Ja, liegt daran. Das der Contesttype von GitHub falsch ist. Muss man halt Mal auf z.B. s3 hochladen... Und die Links ändern. Aber du kannst auch die Audios von sounds.support-pp.de herunterladen

**Comment by TheUndex** [comment]
Anscheinend ist das andere Problem untergegangen. Ich hatte zwei Probleme beschrieben...
"ich hatte mir jetzt die neuste Version des Support++ Scripts installiert und mir ist da direkt etwas aufgefallen. Das Problem ist, dass wenn ein User in den Channel mit dem Bot geht, wird dieser ersteinmal einen Nachricht bekommen und soll aus den verschiedenen Themen wählen. Erst wenn ein Thema ausgewählt wurde, spielt der ausgewählte Track ab. Jedoch sollte es nach meiner Meinung der Fall sein, wenn ich in den Channel joine, der ausgewählte Track sofort abspielt."
