### ISSUE TITLE
Vorschlag: Client UID Unterstützung und 2. Vorschlag

### ISSUE THREAD

**Issue by Leutech** [Support-pp/Support-pp#38]
Hallo ich habe da einen Vorschlag zum Support ++ und zwar wäre es nicht schlecht, das man bei den Supporter und Ignorierte und allgemein bei den Einstellungen, wo man die Server Gruppen ID's einstellt, mit die Client UID's mit einbindet. Bzw meine ich damit, das man anstelle Server Gruppen ID oder auch mit Server Gruppen ID's auch Client UID's angeben kann und auch nur diese Client's eingebunden werden.

Mein 2. Vorschlag wäre, das man bei der ChannalEdit Sektion dort wo man die Support Zeiten einträgt, auswählen kann ob man überhaupt Support Zeit Unterstützung haben möchte und falls nicht die Channelbeschreibung (Wenn der Support Geschlossen ist), diese Nachricht nicht da ist.

**Comment by VerHext** [comment]
@Leutech zum zweiten Vorschlag, wir haben in der Version 2.6.2 ein Bug behoben #61 . Wenn nun keine Channel Beschreibung gesetzt wird, ignoriert Support++ die Beschreibung. Also ein überschreiben ist so nicht mehr möglich.

Und wir haben überlegt, aber wir werden keinen Client UID's hinzufügen. Sorry.
