### ISSUE TITLE
error running script

### ISSUE THREAD

**Issue by CreechYT** [Support-pp/Support-pp#46]
Sinusbot Version: 1.0.0-alpha.4-311d85f

Support++ Version: 2.5.1

Ubuntu 18.04.1 LTS

Hab einen neuen Fehler seit heute, und es geht auch nix mehr. 

2019/01/21 23:35:56 e9a2d92c 88c06fd2 PLUGIN error running script: Uncaught exception: Error: Panic during callback "Get": runtime error: invalid memory address or nil pointer dereference
at support-pp:4044:18
          if (store.get("newsletter-mail") != "") {
                    ^
Stack trace: Error: Panic during callback "Get": runtime error: invalid memory address or nil pointer dereference
    at support-pp:4044:19
2019/01/21 23:35:56 e9a2d92c 88c06fd2 WARN   could not run script: support-pp: Uncaught exception: Error: Panic during callback "Get": runtime error: invalid memory address or nil pointer dereference
at support-pp:4044:18
          if (store.get("newsletter-mail") != "") {
                    ^
Stack trace: Error: Panic during callback "Get": runtime error: invalid memory address or nil pointer dereference
    at support-pp:4044:19

Dachte ist ja nur der Newsletter(Email ist korrekt hab auch schon eine bekommen). Unter den Commands (!help) sehe ich auch die von Support++ nicht mehr gelistet.

Log: https://pastebin.com/64eLZQ9K

Config: https://ibb.co/MpHBg3j

**Comment by CreechYT** [comment]
Mein Script läuft leider immer noch nicht, selbe Fehler. Gibt es schon was neues da ich schon etwas drauf angewiesen bin. Danke im Voraus :)

**Comment by VerHext** [comment]
Wir können das Problem nicht rekonstruieren. Nutzt du die neuste sinusbot Version? Und die 2.51 von Support++?

**Comment by CreechYT** [comment]
Sinusbot: 1.0.0-alpha.4-311d85f
Support++ 2.5.1

**Comment by VerHext** [comment]
The issues is based on an old sinusbot bug.
I close this bug report now.
