### ISSUE TITLE
Fehler: Supportbot verteilt keine Pokes

### ISSUE THREAD

**Issue by cedr203** [Support-pp/Support-pp#57]
Version: 2.6.0
OS: Linux Debian 9

Hallo, mein Sinusbot kann keine User anstupsen.
Wenn User den Support-Channel betreten, erhalten diese die eingestellte Nachricht vom Bot. Allerdings stupst er keine Teammitglieder mehr an.
Vor einiger Zeit hat fehlerfrei funktioniert. Mittlerweile heißt es im Instanz-Log aber immer **Could not poke: invalid parameter size**
Habe auch nochmal nachgeschaut, die Bot-Rolle hat genug Berechtigungen, um mich und Team-Ränge anzustupsen. 

Einstellungen im Support++ Script:
https://prnt.sc/qzq422
https://prnt.sc/qzq4ae
https://prnt.sc/qzq4m4
https://prnt.sc/qzq4w6
http://prnt.sc/qzq589

Instanz-Log: https://pastebin.com/7CnY4y6q
Bot-Log: https://pastebin.com/HYRts8FT
Sinusbot Config: https://pastebin.com/bCip7hMm

Vielen Dank für die Hilfe :)

**Comment by VerHext** [comment]
Besteht das Problem in der Version 2.6.0 noch?
